### ISSUE TITLE
Non-deterministic get_version function

### ISSUE THREAD

**Issue by beczkowb** [allegro/bigflow#194]
Currently, the `bigflow.version.get_version` function adds a random suffix to the version if the repository is dirty. There are 2 problems with that fact:

- A developer has to use the function only once, otherwise, a developer can get 2 different versions
- When a user runs `build-image/dags/package` commands separately, each command might generate a different version

We need to make the suffix generator deterministic.

**Comment by anjensan** [comment]
Link #154
