### ISSUE TITLE
Publish docker images via registry (no real images inside .image)

### ISSUE THREAD

**Issue by anjensan** [allegro/bigflow#241]
Currently 'bigflow build' export docker image to local file. 'bigflow deploy' then loads this file to local registry, which takes enormous amount of time for big images.

Partial solution for this (at least for local development) is to not delete image from local registry, but write docker hash into "./image/image-$version.txt" (fake artifact). Then 'docker deploy' will read this '.txt' file and use image from local registry.
Add optional cli-flag to control behaviour.

**Comment by beczkowb** [comment]
.tar images are for ci/cd plans

**Comment by beczkowb** [comment]
done
