### ISSUE TITLE
find_or_create_setup_for_main_project_package default arguments value

### ISSUE THREAD

**Issue by beczkowb** [allegro/bigflow#86]
The [`find_or_create_setup_for_main_project_package`](https://github.com/allegro/bigflow/blob/49f5af02fc95566ba8423bdb7169b8a63f4a324a/bigflow/resources.py#L136) function takes 2 parameters. Both arguments can be optional.

Make the `search_start_file` argument optional by providing a default value. The default value should be `Path` to a [caller module file](https://stackoverflow.com/questions/1095543/get-name-of-calling-functions-module-in-python).

Make the `project_name` argument optional by providing a default value. The default value should be a top-level package name of a caller. For example, let us say that you use the `find_or_create_setup_for_main_project_package` function from the `caller_module` in the following package tree:

```
my_top_package/
    __init__.py
    my_bottom_package/
        __init__.py
        caller_module.py
```

In that case, the default `project_name` value should be `'my_top_packge'`.

**Comment by Tismas** [comment]
Can I work on this?

**Comment by beczkowb** [comment]
@Tismas sure. If you have some questions - ask :)

**Comment by beczkowb** [comment]
@Tismas Merged, thank you for the contribution!
