### ISSUE TITLE
Removing the optional env variables prefix from Config class

### ISSUE THREAD

**Issue by beczkowb** [allegro/bigflow#99]
Currently, a user can set a custom prefix to the environmental variables in the Config class. The problem is that in many places we assume that the prefix has the default value. Currently, it makes no sense to keep that as customizable, it needs to be removed.

**Comment by anjensan** [comment]
Feature was removed from documentation of `bigflow.Config`
It is still used internally however => we are going to keep it for now. Close this issue.
